### ISSUE TITLE
Cleanup todo screen

### ISSUE THREAD

**Issue by FoxyHunter7** [FoxyHunter7/TaskiFox-Android#2]
- [ ] fix weather misalignment
- [ ] show todos that are in the past in seperate top red display
- [ ] show button to access history
    - _if not enabled in the settings, show a popup explaining that it's disabled_
    - _by default archiving should be for 1 week_
- [ ] fix last todo item being hidden under te add button
    - _by increasing the inner padding so that when the end of the lazycolumn is reached, the last item is above the button_
