### ISSUE TITLE
Polish add todo screen

### ISSUE THREAD

**Issue by FoxyHunter7** [FoxyHunter7/TaskiFox-Android#5]
- [ ] attempt to reduce the lag
- [ ] make project field a dropdown
- [ ] enhance input validation
